Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 60

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/*'
    - 'db/fixtures/**/*'
    - 'tmp/**/*'
